repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks 
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: detect-private-key
      - id: no-commit-to-branch
        args: [--branch, main]

  - repo: https://github.com/psf/black 
    rev: 23.9.1
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8 
    rev: 6.1.0
    hooks:
      - id: flake8

  - repo: https://github.com/PyCQA/bandit 
    rev: 1.7.5
    hooks:
      - id: bandit

  - repo: https://github.com/pre-commit/mirrors-mypy 
    rev: v1.4.1
    hooks:
      - id: mypy